import type {
	IExecuteFunctions,
	INode,
	INodeExecutionData,
	INodeType,
	INodeTypeDescription,
} from 'n8n-workflow';
import { NodeConnectionTypes, NodeOperationError } from 'n8n-workflow';

const SCHEMA_VERSION = 1;
const DEFAULT_BLOCKLY_PAYLOAD = JSON.stringify(
	{
		schemaVersion: SCHEMA_VERSION,
		workspace: {
			blocks: {
				languageVersion: 0,
				blocks: [
					{
						type: 'n8n_return_output',
						x: 24,
						y: 24,
						inputs: {
							VALUE: {
								block: {
									type: 'math_number',
									fields: { NUM: 42 },
								},
							},
						},
					},
				],
			},
		},
		javascript: 'return [{ json: { result: 42 } }];',
	},
	null,
	2,
);

type BlocklyCodePayload = {
	schemaVersion: number;
	workspace: Record<string, unknown>;
	javascript: string;
};

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function isExecutionResult(value: unknown): value is INodeExecutionData[] {
	return Array.isArray(value) && value.every((item) => isRecord(item) && isRecord(item.json));
}

function getRunnerErrorMessage(error: unknown): string {
	if (isRecord(error) && typeof error.message === 'string' && error.message.trim() !== '') {
		return error.message;
	}

	return 'JavaScript task runner failed';
}

function parsePayload(value: string, node: INode): BlocklyCodePayload {
	let payload: unknown;

	try {
		payload = JSON.parse(value);
	} catch {
		throw new NodeOperationError(node, 'Blockly payload must be valid JSON');
	}

	if (!isRecord(payload)) {
		throw new NodeOperationError(node, 'Blockly payload must be a JSON object');
	}

	const { schemaVersion, workspace, javascript } = payload;
	if (schemaVersion !== SCHEMA_VERSION) {
		throw new NodeOperationError(node, `Blockly payload schemaVersion must be ${SCHEMA_VERSION}`);
	}

	if (!isRecord(workspace)) {
		throw new NodeOperationError(node, 'Blockly payload workspace must be a JSON object');
	}

	if (typeof javascript !== 'string' || javascript.trim() === '') {
		throw new NodeOperationError(node, 'Blockly payload javascript must be a non-empty string');
	}

	return { schemaVersion, workspace, javascript };
}

export class BlocklyCode implements INodeType {
	description: INodeTypeDescription = {
		displayName: 'Blockly Code',
		name: 'blocklyCode',
		icon: { light: 'file:blockly-code.svg', dark: 'file:blockly-code.dark.svg' },
		group: ['transform'],
		version: [1],
		description: 'Run JavaScript generated by a Blockly workspace',
		subtitle: 'Generated Blockly JavaScript',
		defaults: {
			name: 'Blockly Code',
		},
		inputs: [NodeConnectionTypes.Main],
		outputs: [NodeConnectionTypes.Main],
		properties: [
			{
					displayName: 'Blockly Payload',
					name: 'blocklyPayload',
					type: 'string',
					default: DEFAULT_BLOCKLY_PAYLOAD,
					typeOptions: {
						editor: 'blocklyEditor',
						rows: 8,
					},
				description: 'JSON containing schemaVersion, workspace, and generated javascript',
			},
		],
	};

	async execute(this: IExecuteFunctions): Promise<INodeExecutionData[][]> {
		const node = this.getNode();
		const rawPayload = this.getNodeParameter('blocklyPayload', 0);
		if (typeof rawPayload !== 'string') {
			throw new NodeOperationError(node, 'Blockly payload must be a string');
		}
		const payload = parsePayload(rawPayload, node);
		const executionResult = await this.startJob(
			'javascript',
			{
				code: payload.javascript,
				nodeMode: 'runOnceForAllItems',
				workflowMode: this.getMode(),
				continueOnFail: this.continueOnFail(),
				additionalProperties: {},
			},
			0,
		);

		if (!executionResult.ok) {
			throw new NodeOperationError(node, getRunnerErrorMessage(executionResult.error));
		}

		if (!isExecutionResult(executionResult.result)) {
			throw new NodeOperationError(node, 'JavaScript task runner returned invalid output');
		}

		return [executionResult.result];
	}
}
